### PR TITLE
add partial suport to export events as BIDS

### PR DESCRIPTION
**Pull request by Edouard2laire**

### CODE REVIEW

**Comment by Edouard2laire** [comment]
Let me know if you have time to review this @rcassani  :)

**Comment by rcassani** [comment]
@Edouard2laire, it looks good.
I made minor aesthetic changes

**Comment by rcassani** [comment]
The support for channel-wise events is on TODO

**Comment by Edouard2laire** [comment]
thanks for the change. 

Yes, i left that aside as I didn't have an example of a file with events on specific channels to test. Also, we would need to export the corresponding JSON file based on bids specifications to explain the channel formatting.

**Pull request merged**
