### PR TITLE
Set up BEst plugin and fix panel

### PR DESCRIPTION
**Pull request by aliobaibk**
A follow-up to #389 with:

- A new option to use minFunc without MEX files ([link](https://neuroimage.usc.edu/forums/t/issue-trying-to-compute-surces-wiht-mem-with-eeg-recordings/26910))
- Improved checking for the availability of `fminunc`
- A new option to load a baseline file from the current protocol using a user specified substring ([link](https://neuroimage.usc.edu/forums/t/issue-trying-to-compute-surces-wiht-mem-with-eeg-recordings/26910))
- BEst setup for the plugin manager ([link](https://neuroimage.usc.edu/forums/t/best-toolbox-in-brainstorm-compiled-version/25898))

### CODE REVIEW

**Comment by ftadel** [comment]
This PR is completed with:
- Moving the other BEST functions to the BEST repo: 
https://github.com/multifunkim/best-brainstorm/pull/2
- Moving the BEST plugin to a new Inverse submenu + additional code cleanup: 
https://github.com/brainstorm-tools/brainstorm3/commit/4d27dca25ceda6d0821127b59e7f2ffff7fa5781
- Moving MEM option to the main "Compute sources" panel:
https://github.com/brainstorm-tools/brainstorm3/commit/2516c7ecfe4934b6c941bd76a6d2a34a0ad0093c
image

**Comment by Edouard2laire** [comment]
hello @ftadel and @aliobaibk 

This new PR seems to have broken the corresponding nirstorm process 'process_nst_cmem.m'. The main issue are those lines: 
```
% Options: MNE options
sProcess.options.mem.Comment = {'panel_brainentropy', 'Estimation options: '};
sProcess.options.mem.Type    = 'editpref';
sProcess.options.mem.Value   = @() MEM_option();
```

```
 i tried to change to 
% Options: MNE options
sProcess.options.mem.Comment = {'panel_brainentropy', 'Estimation options: '};
sProcess.options.mem.Type    = 'editpref';
sProcess.options.mem.Value   = @() MEM_option();

function [varargout] = MEM_option(varargin)
    % Install/load brainentropy plugin
    [isInstalled, errMessage] = bst_plugin('Install', 'brainentropy', 1);
    if ~isInstalled
        return;
    end
    varargout=be_main();

end
```

but because panel_brainentropy is not defined it doesn't work :)

**Comment by ftadel** [comment]
@Edouard2laire It's not @aliobaibk's PR that broke nirstorm's processes, it's my follow-up commits.
I've just commented on that on the NIRSTORM issue: https://github.com/Nirstorm/nirstorm/issues/159#issuecomment-823315993

The two plugins are independent and should be able to work independently. Now it's the nirstorm code that needs to be fixed.
The GetDescription() functions are called often and must be as fast and as self-contained as possible. Calling external functions from there is not recommended, and installing plugins from it is impossible. See my comments on the nirstorm issue.

**Comment by ftadel** [comment]
@aliobaibk 
At the moment, I can compile Brainstorm + BrainEntropy, but the execution of the compiled code fails because you manipulate the path in the code. This is not supported in compiled code. You need to remove all the calls to `addpath` and `rmpath` from your code. Consider that all the subfolders have already been added to the path when loading the plugin.

See the error stack trace below:
image

**Comment by ftadel** [comment]
One last request: please consider removing the useless options "MEM" and "Full results" from the MEM process.

**Comment by aliobaibk** [comment]
Hello @ftadel,

BEst has been updated:
- no more `addpath`;
- useless options removed from the process;
- panel returns full path to baseline instead of preloading it.

Thanks

**Comment by ftadel** [comment]
I recompiled Brainstorm with your updated code.
Could you please download today's compiled distribution of Brainstorm from the website and make sure the MEM works correctly with it?
Thanks

**Pull request merged**
