### PR TITLE
Solutions for the high density mesh for MEG with DUNEuro:  integration points and memory 

### PR DESCRIPTION
**Pull request by tmedani**
Hello all, 

@ftadel this PR is for the discussion started in this here: https://github.com/brainstorm-tools/brainstorm3/issues/350,

We have observed this issue from different testings and [users' experiences](https://neuroimage.usc.edu/forums/t/duneuro-fem-doesnt-finish/21977/23?u=tmedani).

The FEM computation of the MEG with high mesh density + the sensors integration points requires very high memory resources and time, which is not possible to perform in most user computers.

The following PR add a subpanel to the advanced Duneuro panel, and it proposes to the user the following options :
-1- Compute the MEG with or without the integration points 
-2- Disable/Enable the memory cache for the FEM computation 
-3- ToDo : compute per block of sensors (under investigation)

image

The first option is self-explained, 
The second, users can disable the usage of the memory cache, then could perform computation with the integration points with high models==> but it's time-consuming,

The third option is under investigation. 

Here is a view of the LF vectors when using or not the integration points:
image

And as @Moo-Marc mentioned, https://github.com/brainstorm-tools/brainstorm3/issues/350#issuecomment-717674309
the error can be in the range of 2% between the two models (in the spherical model).

Please let me know if there any change required in the code.
Best,
Takfarinas

### CODE REVIEW

**Comment by ftadel** [comment]
> The third option is under investigation.

If you keep in it the interface, I'll wait until the code is here.
Otherwise, and if you want me to merge this now, please remove it from the interface.

**Comment by ftadel** [comment]
I posted some code suggestions that I have edited directly in the github editor, and that I haven't tested.
Please excuse if there are any typos in there...

**Comment by tmedani** [comment]
> > The third option is under investigation.
> 
> If you keep in it the interface, I'll wait until the code is here.
> Otherwise, and if you want me to merge this now, please remove it from the interface.

I will remove it from the GUI for this version,
and work on it, it may take some time before the next PR.

**Comment by tmedani** [comment]
hi @ftadel, your suggestions, and comments are included in the last commit. 
the 3rd option will not be displayed on the gui,  
I will work on it and push as soon as I validate its results.

**Comment by ftadel** [comment]
Should I merge this PR now?

**Comment by tmedani** [comment]
Yes please, then it can be tested by the current users (Carsten's students). 
I'm on the third option that may take some time.

**Pull request merged**
