### PR TITLE
add interactive option to view the tensors

### PR DESCRIPTION
**Pull request by tmedani**
New option to view the tensors,
when the tensors are displayed either on the MRI or the Mesh,
-> Shift + uparrow ==> increase the size of the ellipsoid or the line
-> Shift + downarrow==> decrease the size of the ellipsoid or the line
-> Shift + space ==> switch from ellipsoids view to lines and inversely

### CODE REVIEW

**Comment by ftadel** [comment]
I added popup menus to configure the display with a right-click on the figure > FEM tensors > ...

I also reorganized a bit the code, to have all the properties saved in the same structure (the figure Handles structure) instead of putting different parameters in different places (I removed the access to UserData).

**Comment by tmedani** [comment]
Super, 
Thanks for the re-organization, 
I will test this version.

**Comment by tmedani** [comment]
Hi @ftadel 

FYI, not important but sometimes, this error appears when reduce/increase the size of the tensors and scroll with the mouse

image

**Comment by ftadel** [comment]
> FYI, not important but sometimes, this error appears when reduce/increase the size of the tensors and scroll with the mouse

I added a check to prevent getting properties from objects that were already deleted:
https://github.com/brainstorm-tools/brainstorm3/commit/f8c0a79b018e39c3bccb7a1093e96b42207587fb

**Comment by juangpc** [comment]
Hey, this is just great! 👍

**Pull request merged**
