### PR TITLE
Update bst_connectivity.m

### PR DESCRIPTION
**Pull request by danielemarinazzo**
Specified that wPLI is not the debiased one (see https://github.com/brainstorm-tools/brainstorm3/issues/571), and added the debiased version commented below. This until we figure out how to implement the debiased wPLI in time domain

### CODE REVIEW

**Comment by ftadel** [comment]
@Moo-Marc 
Can you please review this PR?
Are there things to change in the documentation or the process GUI?

Thanks

**Comment by Moo-Marc** [comment]
I'm working on a PR for proper file averaging that will incorporate these fixes and allow the debiased version.  We can close this PR once I submit it.

**Comment by danielemarinazzo** [comment]
since this is taking long, wouldn't be good to merge this PR for the moment, which anyway clarifies things albeit some measures still need to be developed?

**Comment by Moo-Marc** [comment]
Hi Daniele,

I expect to get back to this within a few weeks so I'd suggest to wait.  I'd avoid merging a "fix" or new option that is itself known to be problematic (the trial averaging issue).

**Comment by danielemarinazzo** [comment]
Sure nevermind. Just to be clear, this PR is not a fix for the trial averaging, it's just the current version, but with the non debiased wPLI, and the debiased one commented.

**Comment by rcassani** [comment]
The proposed changes were included in PR #632, which was merged in https://github.com/brainstorm-tools/brainstorm3/commit/24e3d224b2f93614f960231a308fd67cb7c85714

**Pull request closed without merging**
