### PR TITLE
Add Lausanne2008 parcellation support for FreeSurfer anatomy import

### PR DESCRIPTION
**Pull request by jguillon**
This PR allows Brainstorm to automatically and properly load `*.annot` files corresponding to the Lausanne2008 parcellation at different scales.

Those files are generated by the [`easy_lausanne`](https://github.com/jguillon/easy_lausanne) software which is a sub-part of the [Connectome Mapper](http://www.cmtk.org/mapper/).

### CODE REVIEW

**Comment by ftadel** [comment]
@jguillon Thanks for the contribution. 
It is now part of the main distribution, simply update Brainstorm to get the updated code.

I also added this entry to the documentation: http://neuroimage.usc.edu/brainstorm/Tutorials/LabelFreeSurfer#Cortical_parcellations

Maybe "myaparc" is not the most informative file tag?...

**Comment by jguillon** [comment]
@ftadel I agree these tags are not optimal, I'll try to PR `easy_lausanne` repo with this suggestion.

And thank you for the doc !

**Comment by AlexChalard** [comment]
Hello @jguillon & @ftadel 

I am not sure how you install/import the Lausanne parcellation into Brainstorm.
I used CAT12 for MRI segmentation, with CAT12 can I use the Lausanne parcellation or do I need Freesurfer segmentation .

Thank you

Best,

Alex

**Comment by ftadel** [comment]
At the moment, Brainstorm imports automatically the Lausanne segmentation from files named lh.myaparc_36, lh.myaparc_60, lh.myaparc_125 and lh.myaparc_250 in a FreeSurfer folder. 
https://github.com/brainstorm-tools/brainstorm3/blob/master/toolbox/io/import_label.m#L628

I don't know what's the status of the code to compute this Lausanne segmentation, or whether it runs on the CAT12 output, you need to ask the authors of this code and method.

**Pull request merged**
