### PR TITLE
Add timeout to GitHub downloads

### PR DESCRIPTION
**Pull request by mpompolas**
Files that needed to be downloaded from GitHub sometimes failed for no apparent reason.

Added multiple attempts for downloading until a timeout expires

### CODE REVIEW

**Comment by ftadel** [comment]
What are you merging with what in order to have 53 files modified?

**Comment by mpompolas** [comment]
This is annoying. 

Please just look at the latest commit ("Downloads from GitHub are attempted multiple times, until a timer expires"):

https://github.com/brainstorm-tools/brainstorm3/pull/194/commits/bf76806e94fccdc1f0b774d9c33658a114d434fe


Is it possible to merge with only the latest commit, or should I try to create a new fork?

**Comment by ftadel** [comment]
@martcous Could you Konstaninos clean his branch?
Thanks

**Comment by martcous** [comment]
Should be all cleaned up now!

**Comment by ftadel** [comment]
Thanks

I started some heavy code rework modifying hundreds of files: the deletion of the redundant field "samples" in the events structures (as a preamble to adding more descriptive fields to the events).
I will finish my modifications commit them in the a few days, and then this PR should merge in nicely (as it is not modifying any line with ".samples" in it). 
Does it work for you guys?

**Pull request merged**
