### PR TITLE
Cut FEM mesh / remove bottom part

### PR DESCRIPTION
**Pull request by tmedani**
Hello, 

This function allows us to cut and remove the bottom part of the mesh.
This could be useful in the case where the positions of the sensors are only the top part of the head,
in this case, the bottom part is not needed and can save computation time.

with this version, the user can call it by right click on the FEM mesh and set a ratio to remove. 
The default value is 1/3, but the user can change it. 

Brainstorm will create a new head model and save it to the database.

this issue is discusses [here ](https://github.com/brainstorm-tools/brainstorm3/issues/293)

image
 
@ftadel this is the first version and I think it may be better to include it to the main [function process.m](https://github.com/brainstorm-tools/brainstorm3/blob/master/toolbox/process/functions/process_fem_mesh.m) ?

Let me know if I have to change the code and add it to process_fem_mesh.m

Thanks

### CODE REVIEW

**Comment by ftadel** [comment]
There are two problems with the way this function is designed:
- It requires the user to do a few trial and errors to get a good value that doesn't cut too much
- Cutting at z=z0 works in some cases, but won't work if the T1 is not realigned in a FreeSurfer-like orientation. In some cases the head is tilted, or the angle of the MRI slices is not strictly an axial plane...

The defacing code I initially pointed at cuts below a plane with a equation in MNI coordinates. This solves both issues. You just need to define the equation of your plane once, and it will be applicable to ALL the subjects without any individual tweaking, and it's independent on the orientation of the MRI scan. 
https://github.com/brainstorm-tools/brainstorm3/blob/master/toolbox/process/functions/process_mri_deface.m#L202

I strongly encourage you to consider this kind of solution.

**Comment by ftadel** [comment]
Another concern:
Wasn't the goal to minimize the computation time with SimNIBS? 
Shouldn't we cut the volume before running the segmentation, rather than after?

**Comment by tmedani** [comment]
> * It requires the user to do a few trial and errors to get a good value that doesn't cut too much

agree

> * Cutting at z=z0 works in some cases, but won't work if the T1 is not realigned in a FreeSurfer-like orientation. In some cases the head is tilted, or the angle of the MRI slices is not strictly an axial plane...

Ok, thanks for letting me know this, I thought that all the bst models are oriented in the same way. 


> The defacing code I initially pointed at cuts below a plane with a equation in MNI coordinates. This solves both issues. You just need to define the equation of your plane once, and it will be applicable to ALL the subjects without any individual tweaking, and it's independent on the orientation of the MRI scan.
> https://github.com/brainstorm-tools/brainstorm3/blob/master/toolbox/process/functions/process_mri_deface.m#L202
> 
> I strongly encourage you to consider this kind of solution.

will check it, this is the clean method. 




> Another concern:
> Wasn't the goal to minimize the computation time with SimNIBS?
> Shouldn't we cut the volume before running the segmentation, rather than after?

initially, it was the idea, and then the idea to cut the mesh is proposed in this [discussion](https://github.com/brainstorm-tools/brainstorm3/issues/293)

since we can do both, I think we can integrate both methods. It will give more flexibility for the users.
do you agree?

**Comment by tmedani** [comment]
Hi, 
again this is great, 

I think with Z = -85, 
there is only 10 mm from the lower part of the skull to the cutting plan


image
image


So as you said this is slightly high. 


I have checked with  Z = -115, and  there is ~ 40mm 

image
image

Let's use this as the default value since it fits what is said in this paper 
https://onlinelibrary.wiley.com/doi/full/10.1002/hbm.24754


image


And their figures fit better the cut at **Z = 115**

image


We should explain this on the tutorial since this is also related to the position of the sensor. 


btw, a small bug, the 'Get Coordinates' panel is not working on the FEM mesh display. 
image

Thanks & A+

**Pull request closed without merging**
