### PR TITLE
[bugfix] Improve nirs unit management

### PR DESCRIPTION
**Pull request by Edouard2laire**
This is the first fix for #370. It seems to be fixing the issue of attributing mmol unit to doD or raw data.

### CODE REVIEW

**Comment by Edouard2laire** [comment]
I think this will soon be ready to be pushed. Just need to do few more test. I also added a function to be able to use SI prefix instead of any power of 10. I think you could use it also to simplify the code for EEG to automatically use pA. :)

**Comment by ftadel** [comment]
Indeed, this would require to carry this along many additional functions...

Is it really not possible to guess the units of NIRS scouts time series?

**Comment by Edouard2laire** [comment]
Ok; This is ready to be pushed for me. Let me know if you have any comments. 

> Is it really not possible to guess the units of NIRS scouts time series?

It might be doable, but I have to admit that I don't like guessing values that are already saved :)

**Comment by Edouard2laire** [comment]
Actually, don't push it.  There is a very annoying bug... 
Most of the signal are displayed correctly, unless if when viewing a signal, you select a channel and use 'View selected channel'. In that case, the get_unit function is called again but the displayed unit doesn't match the unit in the file anymore. 

Let say the signal is in micromol/l and stored as mmol/l. When opening it, it will be changed to micromol/l for display and display unit is changed to  micromol/l; but if viewing a specific channel, Brainstorm seems to re-read the file as mmol/l while thinking it is micromol/l and therefore think the appropriate unit is 'picomol/l'.  (note the scaling doesn't change, only the displayed unit)




Screenshot from 2021-11-01 22-45-18

**Comment by ftadel** [comment]
I did the display units changes blindly: can you please make sure it works for you?

The duration display modification you proposed was not working when displaying short epochs (with timeunits=ms).
I proposed something simpler, this way the time units are always consistent.

Let me know when this is ready for merging.

**Comment by Edouard2laire** [comment]
I tried on a few files; and it seems it's working. Thanks a lot :)

**Pull request merged**
