### PR TITLE
Bugfix cnx display units

### PR DESCRIPTION
**Pull request by rcassani**
Handle `DisplayUnits` for connectivity TimeFreq files
Fixes issue reported in: https://neuroimage.usc.edu/forums/t/39543

### CODE REVIEW

**Comment by ftadel** [comment]
> We could use [yyaxis](https://www.mathworks.com/help/matlab/ref/yyaxis.html) to put the label on the left side of the colorbar, but this function is for Matlab16b or newer to have something like below. What do you think?

The vertical option is also cut, so this is not a correct solution.
Maybe some units names could be shortened specifically when being displayed as a colorbar legends?
"Magnitude-squared coherence" => "Coh"

**Comment by ftadel** [comment]
Other than that, it looks great!
Thanks

**Comment by rcassani** [comment]
> Maybe some units names could be shortened specifically when being displayed as a colorbar legends?

Sound good! I'll use their short names and be sure they are in the GUI and connectivity page

**Comment by rcassani** [comment]
Since connectivity images and graphs are two representations of the same information, it seems logic to use the same colorbar (position and size). Shortening some unit labels may introduce some confusion; now if the string is longer than the available space, it is vertically shown (without `yyaxis` thus no back-compatibility issue). This is the result:
image

**Pull request merged**
