### PR TITLE
new default colormaps

### PR DESCRIPTION
**Pull request by ranakh23**
New default colormaps to better represent the underlying data:

Non perceptually uniform colormaps either hide details in the data or over accentuate minor changes. This can cause distortions in how the pattern is perceived and interpreted. In general, a good colormap should have the following criteria :  
-  Perceptually uniform (Delta color is equal in all delta data) 
-  Colorblind friendly 
-  Good grayscale conversion 
-  Look nice! 

To assess perceptual uniformity, we can look at the perceptual deltas of both the colormap and its grayscale version. This is essentially the derivative of the colormap in perceptual space with respect to the data. The "perceptual deltas" plot should make a simple horizontal line.

The new colormaps were created using the viscm tool in python, using the CAM02-UCS colorspace.

Brief comparison of the new and previous colormaps:
[comparison.pdf](https://github.com/brainstorm-tools/brainstorm3/files/3049544/comparison.pdf)

### CODE REVIEW

**Comment by ftadel** [comment]
@ranakh23 Thank you for this great contribution!!

@sbaillet Should we switch the default source colormap to magma? (see examples in the attached PDF)

**Comment by ftadel** [comment]
@ranakh23 I merged your PR to bst-java, and would like to merge this one as well. But I cannot commit to changing abruptly all the default colormaps this way, it has to be discussed with all the PIs associated to the project.

Can you please split your PR in two: 
1) Add the support all the colormaps => I will merge this one asap
2) Change the defaults => this might not happen immediately...

Thanks!

**Comment by ftadel** [comment]
The modified blue-red-white colormap has actually a name in matplotlib: RdBu_r
Even if this is a horrible name, it would be better to align on this...
https://matplotlib.org/users/colormapnorms.html

This colormap is used by default in MNE-Python, a Python package that also processes MEG and EEG recordings: 
https://martinos.org/mne/dev/auto_tutorials/plot_visualize_evoked.html
https://github.com/mne-tools/mne-python/blob/master/mne/viz/topomap.py#L191

Could you please make this change?
Then I'll review and merge your PR.

Thanks again for this great work!

**Comment by ranakh23** [comment]
Sure ! Should I change the colormap too or just the name? It is very similar but not exactly the same. 

I'm glad you liked it :)

**Comment by ftadel** [comment]
It would be better to use the exact same colormap as the others, right?
Can you get it directly from matplotlib?

**Comment by sbaillet** [comment]
Hi Rana:

Please review the colormap in question and make sure it meets your criteria. If not, please use yours and give it a funky name - thanks.

Sylvain.

On Apr 17, 2019, at 1:40 PM, Francois <notifications@github.com<mailto:notifications@github.com>> wrote:


It would be better to use the exact same colormap as the others, right?
Can you get it directly from matplotlib?

**Comment by ftadel** [comment]
Please let me know when this is ready to be tested and merged.
Thanks

**Comment by ranakh23** [comment]
Hello again both!

I checked the RdBu colormap. It is made in the CIELAB space. While this is also a perceptual color model, it is not so good at estimating brightness and hue. Here's its evaluation in CIECAM02-UCS space:

image

I edited a few things in this PR and made another PR for the java repo again. 

Also, I made an **attempt** at naming the colormaps and followed the trend of Parula and Viridis which are name after animals, let me know what you think 🤣 : 

image

I couldn't find an older version of Matlab to test the code on btw (only tested on Matlab 2017a). 

If you have any more suggestions please let me know!

**Comment by ftadel** [comment]
Ok, I will merge this soon.

In the meantime, it would be great if you could add a summary of your work as an "Advanced" section at the end of the online tutorial "Colormaps":  
Which default colormaps were replaced, why the old default colormaps were inappropriate, why the new ones are better. No need to give a full lecture on color theory, clickable references will do the job. And include the image with the animals :)
https://neuroimage.usc.edu/brainstorm/Tutorials/Colormaps

This way we'll have some documentation explaining the abrupt changes we're submitting to the users.
Thanks!

**Comment by ftadel** [comment]
(send me an email so I can send you back the instructions to create an account on the wiki)

**Comment by ranakh23** [comment]
I am working on the report as well as a web version of it. Almost done!

**Comment by ftadel** [comment]
Good!
Please include your report directly on the Brainstorm website, so that all the documentation is available at the same place (and searchable easily).
Unless Sylvain asked you explicitly for a separate written report, the online version would be sufficient. Just add your name at the top of the page (and repeat it at the beginning of your section) to indicate you're the author of it.

**Comment by sbaillet** [comment]
All approved!

Best wishes,

Sylvain.
-
Sylvain Baillet, PhD
Professor, Montreal Neurological Institute
McGill University
> more<https://goo.gl/591JdQ>

On Apr 23, 2019, at 12:07 PM, Francois <notifications@github.com<mailto:notifications@github.com>> wrote:


Good!
Please include your report directly on the Brainstorm website, so that all the documentation is available at the same place (and searchable easily).
Unless Sylvain asked you explicitly for a separate written report, the online version would be sufficient. Just add your name at the top of the page (and repeat it at the beginning of your section) to indicate you're the author of it.

**Comment by ftadel** [comment]
Some technical fixes added here (normalized file names...): 
https://github.com/brainstorm-tools/brainstorm3/commit/2518a46779ab995e80285c531177391258d27e5e

**Comment by juangpc** [comment]
Hi, 

While reviewing the tutorials I'm finding the topoplots with the new default color scheme (which I like very much) now don't match what you actually get as result of following the tutorial steps. 

image

If you think the tutorial images should be updated, I can help with that.

**Comment by sbaillet** [comment]
Thanks Juan: I think that’d be fantastic if you could please help with that indeed!

Best wishes,

Sylvain.
-
Sylvain Baillet, PhD
Professor, Montreal Neurological Institute
McGill University
> more<https://goo.gl/591JdQ>

On Apr 26, 2019, at 12:01 PM, Juan <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

While reviewing the tutorials I'm finding the topoplots with the new default color scheme (which I like very much) now don't match what you actually get as result of following the tutorial steps.

[image]<https://user-images.githubusercontent.com/8955424/56820643-1440c580-6812-11e9-9b15-c16e053c9b3d.png>

If you think the tutorial images should be updated, I can help with that.

**Comment by ftadel** [comment]
That would be great if you could help with this! 
I guess you realized this represents a lot of work, there are hundreds of screen captures to modify...

These new colormaps were added this week, maybe we'll realize soon we have to modify them. I suggest we wait for a few weeks (or months) before starting to update all the screen captures of all the tutorials, so we don't have to do it twice.

**Comment by tmedani** [comment]
Hi, 
I will also sift through the tutorial in the next days/weeks to train me better at the differents parts of Brainstorm.
In the sametime I could make screenshots that will be used to update the tutorial.

Best regards 
Takfarinas

**Comment by ftadel** [comment]
@tmedani @juangpc 
Maybe you can split the work so that you don't do the work twice.

In order to preserve some homogeneity across the pages, I suggest the following procedure for updating each screen capture:
- Download the existing image (in your browser: right-click on the image > save as)
- Open it with GIMP (or equivalent)
- Change the color mode from indexed to RGB (menu Image > Mode > RGB)
- Resize the Brainstorm figure with the new colormap to fit the existing figure (from the existing image)
- Copy the window to the clipboard with ALT+PrintScreen
- Paste it into GIMP with CTRL+SHIFT+V (to paste in a new image)
- Select the center of the image (leave out the window frame)
- Copy it: CTRL+C
- Paste it in the screen capture downloaded from the website
- Export the modified image (CTRL+SHIFT+E) and replace the existing one
- On the tutorial web page: Menu > Attachments > select the modified image
- (don't forget to check the box "Erase existing attachments with the same name" - otherwise it wouldn't do anything but the corresponding warning is easily unnoticed)

Would this work for you?

For some images it might make more sense to just do a simple screen capture and update it, but I would prefer avoiding having a mix of window frames (windows 7, windows 10, ubuntu, xfce, macos...)

Another annoying thing can be the image ratios: Most of the images in the tutorials are resized. If you replace an existing image with an new image with different dimensions, the page would use the old dimensions without respecting the height/width ratio of the new image, causing really ugly display.
Two solutions to fix this: 1) edit the page in TEXT mode and fix the dimensions manually, or 2) in GUI mode delete the image, add it again, save, edit again, resize. Both solutions are painful and prone to errors, and in the end, I found it more practical over the years to just keep the same image size and only edit portions of it.

Thanks to you both for offering your help with this!

**Comment by juangpc** [comment]
Yeah, it works for me. @tmedani I'll follow you.
In relation to @ranakh23 fast comment. I'm curious, will the old images be kept in the tutorials version control? (Or maybe we shall keep a copy of them).

**Comment by ftadel** [comment]
@juangpc The attachments are not versioned. Erased versions are deleted for good.

@tmedani If you want to dive in the webserver management as well, maybe you could do a full backup of the wiki before you start updating the screen captures.

I added you both to the Admin groups on the wiki, so you can have access to some useful information:
https://neuroimage.usc.edu/brainstorm/NeuroimageAdmin

**Comment by tmedani** [comment]
@ftadel  Thanks I will have a look & see how it works.

**Pull request merged**
