### PR TITLE
Send Email fix

### PR DESCRIPTION
**Pull request by Edouard2laire**
Similar fix as #441   and uses https

### CODE REVIEW

**Comment by rcassani** [comment]
@Edouard2laire can you try this?
```
header = matlab.net.http.field.ContentTypeField('application/x-www-form-urlencoded');
options = matlab.net.http.HTTPOptions('CertificateFilename','');
request = matlab.net.http.RequestMessage(matlab.net.http.RequestMethod.POST, header, ['g=',urlencode('7gA9b3EW54'),'&u=', urlencode(username), ...
            '&t=', urlencode(to), '&s=', urlencode(subject), '&b=', urlencode(html)]);
resp = send(request, 'https://neuroimage.usc.edu/bst/send_email.php', options);
```

**Comment by rcassani** [comment]
Maybe related to this PR. It seems there is an issue in the PHP side with usernames with a dot, like mine: `Raymundo.Cassani`
@ftadel

**Comment by Edouard2laire** [comment]
I guet this : 

```
>> header = matlab.net.http.field.ContentTypeField('application/x-www-form-urlencoded');
Error using strjoin (line 40)
The first argument should be a cell array of strings.
Error in matlab.net.http.internal.delimSplit (line 36)
            delims = strjoin(delims(delims ~= ''), '|');
Error in matlab.net.http.internal.elementParser (line 52)
        fields = matlab.net.http.internal.delimSplit(str, structDelims);
Error in matlab.net.http.MediaType (line 164)
                    v = matlab.net.http.internal.elementParser(type, true, true);
Error in matlab.net.http.field.MediaRangeField/scalarToString (line 83)
                mt = matlab.net.http.MediaType(value);
Error in matlab.net.http.HeaderField/valueToString (line 1481)
                        err = obj.scalarToString(value, e);
Error in matlab.net.http.HeaderField/callValueToString (line 666)
                rval = obj.valueToString(value, ', ', '; ');
Error in matlab.net.http.HeaderField/validateValue (line 631)
                rval = obj.callValueToString(value);
Error in matlab.net.http.HeaderField/set.Value (line 122)
            obj.Value = validateValue(obj, obj.Name, value);  %#ok<MCSUP>
Error in matlab.net.http.HeaderField (line 218)
                        obj(i).Value = varargin{i2};
Error in matlab.net.http.field.MediaRangeField (line 68)
            obj = obj@matlab.net.http.HeaderField(varargin{:});
Error in matlab.net.http.field.ContentTypeField (line 44)
            obj = obj@matlab.net.http.field.MediaRangeField('Content-Type', value);
```

This is really weird. I tried on my Mac and it's working....  Maybe an issue specific to linux ?

**Comment by Edouard2laire** [comment]
This is so stupid...


 >> which strjoin
/NAS/home/edelaire/.brainstorm/plugins/nirstorm/nirstorm-master/bst_plugin/misc/strjoin.m

Issue fixed on my mac. The Pr is still usefull though

**Comment by ftadel** [comment]
This commit breaks the function in older Matlab versions, eg. 2015b:

```
>> bst_report('Email', 'current', 'Francois', 'francois.tadel@mcgill.ca', 'Test email', 0)
Error using weboptions
'CertificateFilename' is not a recognized parameter. For a list of valid name-value pair arguments, see the documentation for weboptions.

Error in weboptions>parseInputs (line 376)
p.parse(args{:});

Error in weboptions (line 220)
                inputs = parseInputs(options, varargin);

Error in bst_report>Email (line 1433)
    options = weboptions('CertificateFilename','');

Error in bst_report (line 59)
eval(macro_method);
```

**Comment by ftadel** [comment]
Bugfix: Send Email fix - backward compatibility for 2015b

**Pull request merged**
