### PR TITLE
Resample rate option is now saved when importing in database

### PR DESCRIPTION
**Pull request by martcous**
Per issue #18.
The only downside is that the sampling rate of the file is now no longer shown in that menu. Would you like to add it as a text field?

### CODE REVIEW

**Comment by jeremymoreau** [comment]
Thanks! If it's not too much work, then yes perhaps displaying the sampling frequency next to the text box might be useful, e.g. Resample recordings (sampling freq = 2400 Hz): ______
I wouldn't bother if it's complicate however, since it can be viewed elsewhere and I wouldn't expect most users to change this very frequently (personally, I always sample at 2400 Hz).

**Comment by martcous** [comment]
Added current sampling frequency in resample text with Jeremy's approval ;)

**Comment by ftadel** [comment]
I realized after merging that you were not using the correct option name. I fixed your edits to use the existing field ResampleFreq instead of the non-existing ResampleRate.
https://github.com/brainstorm-tools/brainstorm3/commit/c0b1f3c30a5eabd81e1f9f27f90e83a288570292

**Comment by martcous** [comment]
Thanks Francois!

**Pull request merged**
