### PR TITLE
Invasive neurophysiology toolbox

### PR DESCRIPTION
**Pull request by mpompolas**
Adding here the repo I've been working on for visibility.

WIP

### CODE REVIEW

**Comment by ftadel** [comment]
fixes #489

**Comment by ftadel** [comment]
@mpompolas 
I uploaded the tutorial dataset to the web server (available from the download page)
I've been editing quite a lot all the processes and the tutorials.

The things I still need to do:
- Edit process_spikesorting_supervised.m
- Review the last tutorial: https://neuroimage.usc.edu/brainstorm/e-phys/functions
- Edit the processes introduced in these tutorials

Things that do not work:
- Display of UltraMegaSort2000 output
- DespikeLFP option: Requires Optimization toolbox (fminunc) => I could not test it
- The coordinates of the electrodes are probably a bit random (I took the old channel file you distributed, but this is related to old SCS coordinates...). If you have a solution to export these coordinates in the "world" coordinates of the MRI, that would be great

Things that you can already start working on:
- Proof-reading the edits I made of the tutorial
- Make sure that all the spike-sorting functions and conversion to LFP still work on your end, for various test files

I'll keep on working on this in the next few days, please do not push directly anything here.

**Comment by ftadel** [comment]
I'm done for now!

You can now:
- test all the code, 
- test again all the supported file formats
- proof-read the documentation.

There are the following remaining issues:
1. The processes "PSTH per neuron" and "PSTH per electrode" are not documented in the tutorials.
2. The tutorial section "Raster plot per electrode" should be removed, as it refers to a process that does not exist: https://neuroimage.usc.edu/brainstorm/e-phys/functions#Raster_plots
3. `process_spike_triggered_average.m`: lines 163 and 178: `(divideBy - size(all_labels,2))` can be negative and lead to complex std values, which screw up completely the displays. Please fix.
4. I cannot reproduce your figures in the last tutorial: Can you please double-check the results you get with the current version of the code?
    - Noise correlation: 00-res-corr
    - Spike field coherence: 00-res-SFC
    - Spike triggered average: I get **70 files** and not 53 as documented initially.  And I don't see the nice spike illustrated in your figure. Is it because you used the initial recordings and **not** the LFP epochs, as everywhere else in the tutorial? If you did this and you think it makes sense to illustrate the function, then it needs to be explicit that the user should import both the original recordings and the LFP, for different purposes. 
00-res-avg

It would be great to a have processing script to reproduce all this, but I guess you won't have time to work on this before the end of the week :)

**Comment by mpompolas** [comment]
Thanks for checking everything out. Working on this now

**Comment by sbaillet** [comment]
Thank you indeed, François!

On Apr 26, 2022, at 12:30 PM, Konstantinos ***@***.******@***.***>> wrote:



Thanks for checking everything out. Working on this now

**Comment by mpompolas** [comment]
Pull request has been opened at: https://github.com/mpompolas/brainstorm3/pull/13

Tested spikesorters and Derive to LFP with/without Bayesian Denoising.
All good.

Plexon works.
Intan works.
NWB works.
TDT works.


> There are the following remaining issues:
> 
> The processes "PSTH per neuron" and "PSTH per electrode" are not documented in the tutorials.

My bad. The initial version of the paper had them of Rasterplot per neuron and rasterplot per electrode. After the first revision we changed that to PSTH and in my head these were interchangeable. The correct raster plot function was introduced after the revision.
Updated the website to reflect the correct functions.
Also renamed the function `PSTH per electrode` to `PSTH per channel`.

> The tutorial section "Raster plot per electrode" should be removed, as it refers to a process that does not exist: https://neuroimage.usc.edu/brainstorm/e-phys/functions#Raster_plots
Addressed above.


> process_spike_triggered_average.m: lines 163 and 178: (divideBy - size(all_labels,2)) can be negative and lead to complex std values, which screw up completely the displays. Please fix.

Something is off in this function. I can't reproduce the figures I uploaded on the tutorial after your changes. I'll have to check the STD's when I revisit the function again.


### Figures reproduction
> I cannot reproduce your figures in the last tutorial: Can you please double-check the results you get with the current version of the code?

This is probably due to the fact you used the functions after you did spike-sorting within Brainstorm. I added a wiki-note on the [webpage](https://neuroimage.usc.edu/brainstorm/e-phys/functions) to alert users of this.

> Noise correlation:

It's the same.

> Spike field coherence:

It's the same.

> Spike triggered average: I get 70 files and not 53 as documented initially.

This is due to the fact you now have 70 neurons instead of the initial 53.
However, as I mentioned before, I still can't reproduce the figure. Something has changed.


### TODO
I have to read thoroughly the Tutorial again, but as far as coding goes, the only remaining issue that I see is the function `process_spike_triggered_average.m` to check for the `STDs` visualization and confirm that nothing is off after the changes.

**Comment by mpompolas** [comment]
Update - I run the old `process_spike_triggered_average.m` on your branch after converting to LFP and I can confirm that the produced figure is the same as what I had on the tutorial, with correct display of the STDs as well, therefore the changes introduced on https://github.com/mpompolas/brainstorm3/commit/ae9cd964dfa8decd874ec1544dcfe43690aed2d7#diff-a6c4c697a59feda12f423ab7bcc2b2b6aef1465cb6375e90c778f3422d4c5a2b have led to the deviation.


image

image


We just need to focus on the function

**Comment by ftadel** [comment]
> Pull request has been opened at: https://github.com/mpompolas/brainstorm3/pull/13

Looks good! Thanks for fixing some of my mistakes.
Are you going to merge this into this branch? (invasive_plugins)

> This is probably due to the fact you used the functions after you did spike-sorting within Brainstorm. I added a wiki-note on the [webpage](https://neuroimage.usc.edu/brainstorm/e-phys/functions) to alert users of this.

Thanks for the explanation.

> I run the old process_spike_triggered_average.m on your branch after converting to LFP and I can confirm that the produced figure is the same as what I had on the tutorial, with correct display of the STDs as well, therefore the changes introduced on https://github.com/mpompolas/brainstorm3/commit/ae9cd964dfa8decd874ec1544dcfe43690aed2d7#diff-a6c4c697a59feda12f423ab7bcc2b2b6aef1465cb6375e90c778f3422d4c5a2b have led to the deviation.

Do you have a solution?
Or do you suggest I start again from the original file and re-apply one by one the changes to understand what has gone wrong?
What you call "my branch", is it original brainstorm3 repo? Should I start again from: https://github.com/brainstorm-tools/brainstorm3/blob/master/toolbox/process/functions/process_spike_triggered_average.m?

**Comment by ftadel** [comment]
> Pull request has been opened at: https://github.com/mpompolas/brainstorm3/pull/13

I was not sure how you were planning on cascading the merging of the PR, so I integrated these changes directly in here: https://github.com/brainstorm-tools/brainstorm3/pull/516/commits/d55a3b8ac67ea59be2ff4951357afaf7ad729c44

I added a script for reproducing the tutorial pipeline and figures automatically: tutorial_ephys.m

I fixed the bugs I introduced in process_spike_triggered_average.m.

I think this is ready for merging!
Please confirm.

**Comment by ftadel** [comment]
Process report obtained from the script `tutorial_ephys.m`:
[Brainstorm process report.pdf](https://github.com/brainstorm-tools/brainstorm3/files/8596457/Brainstorm.process.report.pdf)

**Comment by mpompolas** [comment]
Thank you so much for all your help Francois.
Sorry for the delay this week.
I will make the last check tomorrow.

**Comment by mpompolas** [comment]
Updated STA tutorial page.

You can now merge.


Thank you for all your help @ftadel and @sbaillet 


### **SCRIPT**
Last check to do once you merge, is to make sure that the script you created is loaded on the website (note: spiking phase locking and PSTH are not called in the script): https://neuroimage.usc.edu/brainstorm/e-phys/functions#Scripting


### **FUTURE IMPROVEMENT**
One thing that I would suggest to be done at some point in the future, would be to distribute a converted .pl2 file, instead of a .plx, so users don't get discouraged with the initial waiting time that it takes for converting from .plx to .bst

**Comment by ftadel** [comment]
Done!
What a amazing piece of work!

@mpompolas 
Thank you so much for the continued efforts on this project over the past years. I'm sure your work will be extremely useful for lots of people around the world.
I wish you the best of luck and success with your new position. 
Hopefully some day you'll miss academia and come back to work with us :-)

**Comment by sbaillet** [comment]
Just re-iterating Francois’ words of appreciation and encouragement (to come back and work with Brainstorm!).

Cheers,

Sylvain.

On May 3, 2022, at 8:44 AM, Francois ***@***.******@***.***>> wrote:



Done!
What a amazing piece of work!

@mpompolas<https://github.com/mpompolas>
Thank you so much for the continued efforts on this project over the past years. I'm sure your work will be extremely useful for lots of people around the world.
I wish you the best of luck and success with your new position.
Hopefully some day you'll miss academia and come back to work with us :-)

**Pull request merged**
