### PR TITLE
Minor modification on line 1020 to address forum post reporting memory issues with large source grids. 

### PR DESCRIPTION
**Pull request by sbaillet**
Greater memory efficiency; works better for denser source grids and faster execution.

### CODE REVIEW

**Comment by sbaillet** [comment]
Done.

**Comment by ftadel** [comment]
If the idea is just to scale the rows of matrix "Kernel", we'd rather use bsxfun instead:

```
tic; 
diag(Alpha{kk}) * Kernel(Ndx,:); 
toc
Elapsed time is 1.535137 seconds.

tic; 
bst_bsxfun(@times, Kernel(Ndx,:), Alpha{kk}(:)); 
toc
Elapsed time is 0.031496 seconds.
```

@jcmosher Can you please check that this does what you expect from this function?

**Comment by ftadel** [comment]
@jcmosher ?

**Comment by ftadel** [comment]
@jcmosher Can you please just confirm you receive copies of these messages by email?
Thanks

**Comment by ftadel** [comment]
@jcmosher ?............

**Comment by ftadel** [comment]
Anybody still cares about this PR?

**Comment by jcmosher** [comment]
I read the code that Sylvain proposed. Looks good. As he points out, will be far more efficient for dense source grids. What I don't recall is why I would have programmed such a sloppy "diag" in the first place. "spdiags" is the correct approach here.

**Comment by ftadel** [comment]
@jcmosher Thanks

**Pull request merged**
