### PR TITLE
PCA fix sign 1PC

### PR DESCRIPTION
**Pull request by rcassani**
- Handle the sign of the 1st PC

### CODE REVIEW

**Comment by Moo-Marc** [comment]
Hi, Sorry I missed the last meeting, but this scaling doesn't seem to me like the correct "fix" for this.  I'm going to spend more time looking into this this week, but I think there's basically an incorrect assumption of independence between sources by doing PCA like this. Like we had discussed, I'll also look at doing the forward or inverse model "orientation average". For now, I'd leave out the scaling proposed here.

**Comment by Moo-Marc** [comment]
Right.  I mean "orientation" of forward/inverse solution vectors in high-dimensional sensor space.

**Comment by rcassani** [comment]
The power scaling has been moved out of this PR

**Comment by rcassani** [comment]
This change is currently handle in #559

**Pull request closed without merging**
