### PR TITLE
Added SVD warning for process_inverse_2016/2018 with Matlab 2018a

### PR DESCRIPTION
**Pull request by martcous**
Let me know if that is that you had in mind (only shown when interactive, not from a script).

### CODE REVIEW

**Comment by ftadel** [comment]
This would be extremely annoying to have this message every single time for nothing... In crashes in very few cases.
A try-catch block around the calls to bst_inverse_linear_* would be more adapted. You could just rethrow the error with the original message, but adding a note about the SVD changes if Matlab==2018a .

It would be interesting to check if this was fixed with 2018b. Could you do that?

**Comment by martcous** [comment]
Thanks Francois, is this better?

**Comment by ftadel** [comment]
Have you tested if this syntax MException/throw/rethrow works with older Matlab (2008a)?
(With older Matlab versions, I'm not even sure the syntax "try e" works...)
Otherwise, you can probably simply create a new error by calling error()

**Comment by martcous** [comment]
Yes, MException() and rethrow() were introduced in Matlab 2007a. I tested in 2008.
https://www.mathworks.com/help/matlab/ref/mexception.rethrow.html
https://www.mathworks.com/help/matlab/ref/mexception-class.html

**Pull request merged**
