### PR TITLE
Added new Scilearnlab decoding processes

### PR DESCRIPTION
**Pull request by martcous**
With Dimitrios' help, I added two new processes: process_decoding_maxcorr and process_decoding_svm and their supporting scilearnlab library. They will be featured in next week's workshop on machine learning in Brainstorm.

I had to make some minor tweaks to the view_matrix() and figure_image() to display their results properly (to support a Time dimension in the Y axis).

### CODE REVIEW

**Comment by ftadel** [comment]
Are you going to provide a public tutorial and dataset for these new functions?

**Comment by martcous** [comment]
@dimitriospantazis Since we cannot share the dataset we used for the training, did you have another example dataset in mind?

**Comment by dimitriospantazis** [comment]
Hi Martin,

We can share the dataset! But we need to deface the MRI. I was unable to do this before, can someone help?

Thank you,
Dimitrios

**Comment by sbaillet** [comment]
Marc can help (we do that for OMEGA BIDS)

Sylvain.
-
Sylvain Baillet, PhD
Professor, Montreal Neurological Institute
McGill University
@sylvain_baillet<https://twitter.com/sylvain_baillet> - > more<https://goo.gl/591JdQ>

On Jun 18, 2019, at 9:27 AM, Dimitrios Pantazis <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Martin,

We can share the dataset! But we need to deface the MRI. I was unable to do this before, can someone help?

Thank you,
Dimitrios

**Comment by ftadel** [comment]
@Moo-Marc If you master other defacing procedures that are easy to setup on any computer, we should work on adding them to Brainstorm as well.

**Comment by sbaillet** [comment]
I didn’t know that: great!

Sylvain.
—
Professor, Montreal Neurological Institute
Associate Dean (Research), Faculty of Medicine
McGill University.
@sylvain_baillet


On Jun 19, 2019, at 3:57 AM, Francois <notifications@github.com<mailto:notifications@github.com>> wrote:


You can easily deface MRI volumes with Brainstorm now:
https://neuroimage.usc.edu/brainstorm/News#March_2019

FreeSurfer's mri_deface is available only for Linux/MacOS.
The SPM approach (simple plane cutting the volume in two), should work on all the computers, but cuts out some of the most frontal parts of the cortex on some subjects.

Let me know if there are issues with one or the other.

**Comment by dimitriospantazis** [comment]
Thank you Francois,

I defaced the mri and exported it to analyze format. I am now running Freesurfer analysis again to see if it will work correctly.

Best,
Dimitrios

**Pull request merged**
