### PR TITLE
[bugfix] better identify raw file when exporting file

### PR DESCRIPTION
**Pull request by Edouard2laire**
Hello, 

This fix a bug where some raw file would not be identified as raw file during export.

### CODE REVIEW

**Comment by rcassani** [comment]
Hi @Edouard2laire, how did you get to have a file with such a name?
Raw files should have `_0raw` in their names

**Comment by Edouard2laire** [comment]
it was created by https://github.com/brainstorm-tools/brainstorm3/pull/717

**Comment by rcassani** [comment]
> i copied what we did for the synchronisation to get filename (https://github.com/brainstorm-tools/brainstorm3/blob/master/toolbox/process/functions/process_sync_recordings.m#L255 ) :

Yeah, that's not right. It should have been `_0raw`

> It is recognize everywhere else in brainstorm as raw file despite not having _0raw

It does work for most of the cases as different checks for 'raw' type just find the `raw`  string, or check if the loaded `F` is a struct. However, it may have unexpected behaviours, e.g., setting a bad channel for a `_raw` file will not change the `ChannelFlag` inside `F`: https://github.com/brainstorm-tools/brainstorm3/blob/ec632b9c6579a01dad7c05df8919fc4c89c2909f/toolbox/sensors/panel_channel_editor.m#L722 , and in other places that do check for `_0raw`

I'll push the correction on `process_sync_recordings.m` directly on the master

**Comment by Edouard2laire** [comment]
Is there a way I can fix the file already created without having to recompute ?

**Comment by rcassani** [comment]
Apologies for the inconveniences. 
With Brainstorm close, you could renaming the file to add the zero and reloading the Protocol

**Pull request closed without merging**
