### PR TITLE
fixed jsondecode for list of strings

### PR DESCRIPTION
**Pull request by Moo-Marc**
Following Martin adding this feature to bst_jsondecode (https://github.com/brainstorm-tools/brainstorm3/commit/e4d7892ab89b4bb563bcadb6a7748e8b6d8a52fc), I did some debugging.

### CODE REVIEW

**Comment by martcous** [comment]
Thanks Marc! There is an issue that remains with spaces in the strings of a list:
Code: `bst_jsondecode('{"value": ["this is", "a test"]}', 1)`
Output: `value: {' '  'thisis'  ' '  'atest'}`

**Comment by ftadel** [comment]
@Moo-Marc Please let me know when this is ready for merging.

**Review by martcous — APPROVED** [review]
Nicely done, Marc! Looks good on my end.

**Comment by ftadel** [comment]
@Moo-Marc 
Can you please remove the extra indentation you added in `bst_jsondecode.m`?
It makes it impossible to review the actual changes to the file.
Thanks

**Comment by ftadel** [comment]
> the code changed massively, are you sure indentation is the problem?

Please remove the extra white spaces at the beginning of the lines for the first level of indentation, including the header comments.
1) To limit the size of this current diff
2) To follow the convention used in all the Brainstorm functions

Thanks

**Comment by Moo-Marc** [comment]
done

**Comment by ftadel** [comment]
Looks a lot better, thanks!

**Pull request merged**
