### PR TITLE
Installation nirstorm - fix compatibility with Matlab < 2017b

### PR DESCRIPTION
**Pull request by Edouard2laire**
As discussed in #357, the installation script now uses gui_brainstorm('DownloadFile') to download nirstorm from GitHub. 

hs: is that normal that all not only my last commit appears on the commit list ?

### CODE REVIEW

**Comment by ftadel** [comment]
> hs: is that normal that all not only my last commit appears on the commit list ?

You mean, in the brainstorm commit list?
Yes, because I used "squash and merge".
All the individual commits remain documented in the PR.

**Comment by Edouard2laire** [comment]
> > hs: is that normal that all not only my last commit appears on the commit list ?
> 
> You mean, in the brainstorm commit list?
> Yes, because I used "squash and merge".
> All the individual commits remain documented in the PR.

I was meaning when I oppened this PR, GitHub is saying 'Edouard2laire and others added 10 commits 3 days ago'  when I thought it would only show the last one as it is the only one that has not been pushed in the brainstorm branch yet.

**Comment by ftadel** [comment]
Should I remove process_nst_detect_bad.m and process_nst_mbll.m from the Brainstorm distribution, since they are downloaded and overridden by nst_setup.m?

**Comment by Edouard2laire** [comment]
I don't know. 

Maybe it's good to have them as it is signaling to users that you can process nirs data in Brainstorm and it is allowing them to do the very few first steps of nirs processing. On the other hand, If we keep them I should update them based on the recent bugs reported in our GitHub.

**Comment by ftadel** [comment]
It doesn't make sense to have 2 versions of these processes. If they are in the package downloaded by nst_setup, then they should not be in Brainstorm.
I removed them: https://github.com/brainstorm-tools/brainstorm3/commit/c6f4d36472cae87002096cdf768bd8f5afb5b059

What you could do if you want to keep Nirstorm visible in the process list:
- transform nst_setup into a process function process_nst_setup.m, named "NIRSTORM setup" or "Install Nirstorm", or something like that.
- with 3 subfunctions: Status, Install, Uninstall
- a radio_label button offers the choice between Install and Uninstall
- an extra label explains where the files are installed, gives some references about Nirstorm , and the Documentation (Online help) points at the Nirstorm website - see examples in existing processes, like process_mne_maxwell.
- For the callbacks functions of the Update menu, you can call the subfunctions in the process function with the syntax: process_nst_setup('Install') and process_nst_setup('Uninstall')
- And then you delete nst_setup.

It would make Nirstorm install and references much more visible for most users.

**Comment by Edouard2laire** [comment]
Thanks. One issue i just thought of is that people using the compiled version of brainstorm can no longer perform basic nirs analysis. Or do you think it could be possible to have a compiled version of nirstorm too ?

**Comment by ftadel** [comment]
I just noticed what happens in the .brainstorm/process folder when you install NIRSTORM: it copies everything in there...
This folder is meant only for hosting process_...m files, the rest should go in a .brainstorm/nirstorm folder.
Can you please make this change?

> One issue i just thought of is that people using the compiled version of brainstorm can no longer perform basic nirs analysis. Or do you think it could be possible to have a compiled version of nirstorm too ?

I will check if I can compile easily nirstorm together with Brainstorm (in that case, it would simply be available to anybody using the compiled version). Will let you know how this goes.

**Comment by ftadel** [comment]
One other thing to change: In compiled mode, you should not display the menu "Update NIRSTORM" in the Brainstorm window.
If it is available in the compiled package: good, otherwise: it is useless to try and download it.
=> Add a test similar to the one about the Brainstorm update: `if ~(exist('isdeployed', 'builtin') && isdeployed)`

Thanks

**Comment by ftadel** [comment]
I updated the compiled version: now it includes all the NIRSTORM processes, nothing to download on top of it.
https://github.com/brainstorm-tools/brainstorm3/commit/4feee0ef70d1de8fd90528f40d5749140c7b25a9
Could you try if everything seems to work in the current compiled version? (follow the instructions "without Matlab" in the installation page if you don't know how to start it)

The menu "Update NIRSTORM" is now hidden in the compiled version.
If you add a process_nst_setup.m to install/update/uninstall nirstorm, you should add some code at the beginning of the Run() function to stop if in compiled mode (`if ~(exist('isdeployed', 'builtin') && isdeployed)`)

With the current NIRSTORM version, I get some processes reported as invalid, could you please fix this?
```
BST> Invalid plug-in function: "process_nst_OM_from_cap.m"
BST> Invalid plug-in function: "process_nst_OM_from_cortex.m"
BST> Invalid plug-in function: "process_nst_OM_from_head.m"
BST> Invalid plug-in function: "process_nst_cpt_fluences_from_cortex.m"
BST> Invalid plug-in function: "process_nst_cpt_fluences_from_head.m"
BST> Invalid plug-in function: "process_nst_import_head_model.m"
```

**Comment by Edouard2laire** [comment]
> I updated the compiled version: now it includes all the NIRSTORM processes, nothing to download on top of it.
> [4feee0e](https://github.com/brainstorm-tools/brainstorm3/commit/4feee0ef70d1de8fd90528f40d5749140c7b25a9)
> Could you try if everything seems to work in the current compiled version? (follow the instructions "without Matlab" in the installation page if you don't know how to start it)

Thanks a lot. I think most of the functions will work. Optimum montage and fluences might not work as they rely on external software (respectively CPLEX studio and MCXlab). I'll try to do some tests this week. 
> 
> The menu "Update NIRSTORM" is now hidden in the compiled version.
> If you add a process_nst_setup.m to install/update/uninstall nirstorm, you should add some code at the beginning of the Run() function to stop if in compiled mode (`if ~(exist('isdeployed', 'builtin') && isdeployed)`)
> 
Ok. Thanks for the information (i read your prevous messages) . I'll have a busy week as in presenting in our lab meeting Friday but I'll try to have a look as soon as possible.  


> With the current NIRSTORM version, I get some processes reported as invalid, could you please fix this?
> 
> ```
> BST> Invalid plug-in function: "process_nst_OM_from_cap.m"
> BST> Invalid plug-in function: "process_nst_OM_from_cortex.m"
> BST> Invalid plug-in function: "process_nst_OM_from_head.m"
> BST> Invalid plug-in function: "process_nst_cpt_fluences_from_cortex.m"
> BST> Invalid plug-in function: "process_nst_cpt_fluences_from_head.m"
> BST> Invalid plug-in function: "process_nst_import_head_model.m"
> ```

It's weird. I have no error on my side. could you tell me what are the errors detected in the process? you can run process_nst_OM_from_cap('GetDescription') to know why brainstorm is marking the process as invalid. 

Best regards, 
Edouard

**Comment by ftadel** [comment]
> > `BST> Invalid plug-in function: "process_nst_OM_from_cap.m"`
> It's weird. I have no error on my side. could you tell me what are the errors detected in the process? you can run process_nst_OM_from_cap('GetDescription') to know why brainstorm is marking the process as invalid.

Please ignore this report: this was my fault, I moved all the non-process files to `.brainstorm/nirstorm` for the compilation, and forgot to move them back, but then this folder was not added to the path when I restarted Matlab... 

A summary of my other recommendations (no rush - when you have time):
- Move the the non-process files to `.brainstorm/nirstorm`
- Replace `external/nirstorm/nst_setup.m` with `process/functions/process_nst_setup.m` (hidden in compiled mode)
   - You could make the different options to what is already installed (eg. offer the uninstall option only if the process_nst_* are available in the path), but not necessary 
- Menus "Update NIRSTORM" pointing at the process too (eg. `process_nst_setup('Install')`)

**Pull request merged**
