### PR TITLE
Able to debug panel_realtime.m

### PR DESCRIPTION
**Pull request by juangpc**
Hi, 

Being the file as it is right now if you try to set a breakpoint in the file panel_realtime.m an error pops up. 
Commenting this line seems to solve the issue. 

image

### CODE REVIEW

**Comment by martcous** [comment]
I don't think that's an appropriate fix since the variable "count" is used before as well (line 815). Maybe rename it instead? It's complaining because there is a builtin Matlab function called "count".

**Comment by juangpc** [comment]
I agree. I figured that commenting was 'less intrusive' in other peoples code that renaming.

**Comment by juangpc** [comment]
Following your comment...

**Comment by ftadel** [comment]
How can this code even work, since neither count nor count_var are defined before line 815?

@Moo-Marc Do you use this function?

@juangpc What version of Matlab are you using, to get these weird errors in the parser? Did you install Matlab with all the possible toolbox it offers?

@ebock I guess you wrote this? Comments are welcome :)

**Comment by juangpc** [comment]
For the record, shared ver output below.

@ftadel I set a breakpoint in every file in the toolbox and then f10 like crazy to understand how everything goes in this thing we call bst.

```matlab
>> ver
-----------------------------------------------------------------------------------------------------
MATLAB Version: 9.6.0.1072779 (R2019a)
MATLAB License Number: 31337
Operating System: Microsoft Windows 10 Pro for Workstations Version 10.0 (Build 17763)
Java Version: Java 1.8.0_181-b13 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
-----------------------------------------------------------------------------------------------------
MATLAB                                                Version 9.6         (R2019a)
Simulink                                              Version 9.3         (R2019a)
Control System Toolbox                                Version 10.6        (R2019a)
DSP System Toolbox                                    Version 9.8         (R2019a)
Data Acquisition Toolbox                              Version 4.0         (R2019a)
Deep Learning Toolbox                                 Version 12.1        (R2019a)
Image Acquisition Toolbox                             Version 6.0         (R2019a)
Image Processing Toolbox                              Version 10.4        (R2019a)
Instrument Control Toolbox                            Version 4.0         (R2019a)
Optimization Toolbox                                  Version 8.3         (R2019a)
Parallel Computing Toolbox                            Version 7.0         (R2019a)
RICOH MEG Reader toolbox for MATLAB                   Version 1.0.3               
Signal Processing Toolbox                             Version 8.2         (R2019a)
Simulink Control Design                               Version 5.3         (R2019a)
Statistics and Machine Learning Toolbox               Version 11.5        (R2019a)
Symbolic Math Toolbox                                 Version 8.3         (R2019a)
Wavelet Toolbox                                       Version 5.2         (R2019a)
Yokogawa MEG Reader toolbox for MATLAB                Version 1.5.2               
```

**Comment by Moo-Marc** [comment]
I do use the realtime stuff once in a while as a demo, but not in any study so far.  I've made some fixes and edits to our local copy, but as I am planning some more work on it, and as far as I know only our lab uses it, I haven't pushed anything so far.  So I'd suggest Juan to ignore this for now.  

Let me know if there's any indication that it's needed elsewhere and then I can increase the priority on my to do list (right now it's very low).

**Comment by ftadel** [comment]
I haven't heard of anybody else using it.
@juangpc maybe you can close this PR for now and let @Moo-Marc handle the maintenance of this function, as he's the only one who can actually test it.

**Comment by ebock** [comment]
Hi All,
Thanks for all your work on Brainstorm and even on these unstable bits that
were left hanging...and my obvious absence from the conversations...
I think the realtime panel was updated locally at some point and the code
was not updated as part of the main distribution. If you want to fix it, I
suggest you submit the local version of those functions and then debug from
there.
Sorry to leave this to you, but I don't have access to this anymore.

Beth

**Pull request closed without merging**
