### PR TITLE
bump OpenMEEG version to 2.4.1

### PR DESCRIPTION
**Pull request by agramfort**
cc @massich @papadop

### CODE REVIEW

**Comment by massich** [comment]
+1 it works (on my machine)

just running:

```matlab
>> cd ~/repos/brainstorm3/
>> brainstorm
 
BST> Starting Brainstorm:
BST> =================================
BST> Version: 22-Aug-2018
BST> Compiling main interface files...
BST> Emptying temporary directory...
BST> Deleting old process reports...
BST> Loading configuration file...
BST> Checking internet connectivity... ok
BST> Initializing user interface...
BST> Starting OpenGL engine... software
BST> Reading plugins folder...
BST> Loading current protocol...
BST> =================================
 
>> tutorial_epilepsy('/home/sik/Downloads/', '/tmp/report_dir/')
```

Updated Openmeeg from 2.4.0 to 2.4.1

```sh
~/.brainstorm/openmeeg/linux64
❯ LD_LIBRARY_PATH=$PWD OMP_NUM_THREADS=1 ./om_gain --help
./om_gain version 2.4.1 compiled at Aug 22 2018 19:41:28 using OpenMP
 Executing using 1 threads.
```

**Comment by agramfort** [comment]
@ftadel @jguillon can one of you click the green button so we can get back to people on the forum to tell them to just update brainstorm? thanks

**Comment by ftadel** [comment]
It's online and repackaged. 
You can now tell people to update Brainstorm (using the menu Update > Update Brainstorm) and after that, the next execution of OpenMEEG should download the new version automatically.

**Comment by agramfort** [comment]
thanks.

let's hope everything works now...

**Pull request merged**
