### PR TITLE
[bugfix] improve snirf file management

### PR DESCRIPTION
**Pull request by Edouard2laire**
Hello, 

This PR: 
+ Overall improve the saving/loading of snirf files.
+ Removes the EasyH5 and SNIRF toolboxes from Brainstorm source code
+ EasyH5 and SNIRF toolboxes added as optional plugins, to faster retrieve of bugfixes, e.g.:
  + Bug when exporting snirf file (see https://github.com/NeuroJSON/jsnirfy/issues/1)
  + Bug when exporting snirf file (see https://github.com/NeuroJSON/easyh5/commit/e7fc01f7719a67a7d03f143700a93f0329d779e9 )

Edit: Reflect final code in PR

### CODE REVIEW

**Comment by Edouard2laire** [comment]
up :)

**Comment by rcassani** [comment]
@Edouard2laire, I'll check this PR later in the week

**Comment by rcassani** [comment]
Hi @Edouard2laire, with the last commit EasyH5 and JSNIRF(Y) are now available as Plugins. This will allow user to keep up today with the toolboxes and reduce the source code for user that do not use those toolboxes. 

Could you verify that nothing was broken in your PR with this movement?

**Comment by Edouard2laire** [comment]
> Hi @Edouard2laire, with the last commit EasyH5 and JSNIRF(Y) are now available as Plugins. This will allow user to keep up today with the toolboxes and reduce the source code for user that do not use those toolboxes.

I agree; it's much better like that.

> Could you verify that nothing was broken in your PR with this movement?

Tested. it's working. thanks :)

**Pull request merged**
