### PR TITLE
Export ROI as Freesurfer annotation

### PR DESCRIPTION
**Pull request by Edouard2laire**
This PR is doing three things : 
- Give a better error when trying to export multiple ROI using FreeSurfer label format (that only support on ROI per file)
https://surfer.nmr.mgh.harvard.edu/fswiki/LabelsClutsAnnotationFiles

- Export multiple ROI as annotation files   https://surfer.nmr.mgh.harvard.edu/fswiki/AnnotFiles 
- Fix a small bug in the reading of annotation file  https://surfer.nmr.mgh.harvard.edu/fswiki/LabelsClutsAnnotationFiles#Annotationfiledesignsurprise

### CODE REVIEW

**Comment by rcassani** [comment]
> * Export multiple ROI as annotation file

As test, you could try to import the created `.annot` file with **Scout tab > Atlas > Load atlas**

**Comment by Edouard2laire** [comment]
Hello, 

This should be ready. The function write_annotation is from FreeSurfer: https://github.com/freesurfer/freesurfer/blob/dev/matlab/write_annotation.m


There is only one limitation that I am not sure how to address. In the annotation format, each vertex is not associated with a label associated with a name and a color. But each vertex is associated with a color and then the color is associated with the region's name.

 So two scouts cannot be described in an annotation file if they have the same color.  This is for example the case for atlas where the left/right scout have the same color. How should we handle it ?

**Comment by rcassani** [comment]
> There is only one limitation that I am not sure how to address. In the annotation format, each vertex is not associated with a label associated with a name and a color. But each vertex is associated with a color and then the color is associated with the region's name.

The plan would be to set the repeated colors to a small variations of the original. 
I will work on this and add it to the PR

**Comment by rcassani** [comment]
Duplicate colors addressed! 
Can you test the exported `.annot` in FreeView?

**Comment by Edouard2laire** [comment]
it's working well (left freeview, right: Brainstorm) 
Thank you :) 

Screenshot from 2023-07-13 10-12-01


On another, topic, I know you are busy but do you think you would have time to have a look at https://github.com/brainstorm-tools/brainstorm3/issues/630 . I am giving a presentation on Nirstorm on the 20 of July and I would like to try to have this implemented before the presentation  :)

**Comment by Edouard2laire** [comment]
I just thought about something this morning: is it possible to call this code from a script to be able to export the ROI from a script?

**Comment by rcassani** [comment]
It is not possible as it is, as it requires user interaction to set the output file and format.

The non-interactive call for this function, and other functions with Scouts would be a nice-to-have feature

**Pull request merged**
